---
- name: Common
  hosts: all
  roles:
    - common
    - prometheus.prometheus.node_exporter

- hosts: monitors
  roles:
    - monitor
  vars:
    prometheus_targets:
      node:
        - targets: >-
            {{
              groups['all']
              | map('extract', hostvars)
              | map(attribute='inventory_hostname')
              | map('regex_replace', '$', ':9100')
              | list
            }}
          labels:
            env: pi-cluster
