---
- name: Common
  hosts: all
  roles:
    - common
    - prometheus.prometheus.node_exporter

- hosts: rpi
  name: Raspberry pi exporter
  roles:
    - rpi_exporter

- hosts: monitors
  roles:
    - monitor
  vars:
    prometheus_targets:
      node:
        - targets: >-
            {{
              groups['rpi']
              | map('extract', hostvars)
              | map(attribute='ansible_host')
              | map('regex_replace', '$', ':9100')
              | list
            }}
          labels:
            env: pi-cluster

        - targets: >-
            {{
              groups['monitors']
              | map('extract', hostvars)
              | map(attribute='ansible_host')
              | map('regex_replace', '$', ':9243')
              | list
            }}
          labels:
            env: pi-cluster
